use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let migrations_dir = Path::new("migrations");

    if !migrations_dir.is_dir() {
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(migrations_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "sql"))
        .collect();

    entries.sort_by_key(|e| e.file_name());

    let mut parts = Vec::new();
    for (idx, entry) in entries.iter().enumerate() {
        let name: String = entry.file_name().to_string_lossy().into_owned();
        let version = (idx + 1) as i64;
        let base = name.strip_suffix(".sql").map(|s| s.to_string()).unwrap_or(name);
        let content = fs::read_to_string(entry.path()).unwrap_or_default();
        let escaped = escape_rust_str(&content);
        parts.push(format!("({}, \"{}\", \"{}\")", version, base, escaped));
    }

    let list = parts.join(",\n    ");
    let code = format!(
        r#"// Auto-generated by build.rs — เพิ่มไฟล์ .sql ใน migrations/ แล้ว build ใหม่
pub const MIGRATIONS: &[(i64, &str, &str)] = &[
    {}
];
"#,
        list
    );

    fs::write(Path::new(&out_dir).join("migrations.rs"), code).unwrap();

    println!("cargo:rerun-if-changed=migrations");
    println!("cargo:rustc-env=OUT_DIR={}", out_dir);
}

fn escape_rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\r' => out.push_str("\\r"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{{{:04x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
